on:
  push:
    branches:
      - master
  pull_request:

name: Run tests

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.parallel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        parallel: [ 'serial', 'parallel' ] 
        os: [ 'ubuntu-latest', 'macos-latest' ]

    steps:
    - uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build 
      run: cmake -S . -B build 

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        cache: 'pip'

    - name: Turn off parallelization flags
      if: ${{ matrix.parallel== 'serial' }}
      run: |
        cat tests/lib/CMakeLists.txt | grep -v "TEST_CUSTOM_PARALLEL" > .tmp
        cat .tmp
        mv .tmp tests/lib/CMakeLists.txt

    - name: Install package
      run: python3 -m pip install .[testing]
      working-directory: tests

    - name: Run the tests
      run: python3 -m pytest
      working-directory: tests
